services:
  database:
    image: postgres:17.2-alpine3.21
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ElMarchi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.14.0
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - database

  redis:
    image: redis:7.4.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning --requirepass p@ssw0rd_r3kwired
    volumes:
      - ./data:/data

volumes:
  postgres_data:
  data:
